[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "jupygate"
dynamic = ["version"]
description = "Websocket gateway for Jupyter kernels"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Jeremy Howard", email = "github@jhoward.fastmail.fm"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []

[project.urls]
Repository = "https://github.com/AnswerDotAI/jupygate"
Documentation = "https://AnswerDotAI.github.io/jupygate/"

[project.entry-points.nbdev]
jupygate = "jupygate._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "jupygate.__version__"}

[tool.setuptools.packages.find]
include = ["jupygate"]

[tool.nbdev]
