# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jupygate',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/jupygate',
                'lib_path': 'jupygate'},
  'syms': {'jupygate.core': {'jupygate.core.foo': ('core.html#foo', 'jupygate/core.py')}}}
