"""Kernel processes, channels, routing, and the gateway server

Docs: https://AnswerDotAI.github.io/jupygate/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['log', 'IPYMINI_ARGV', 'CHANNELS', 'dumps', 'loads', 'dumps_binary', 'loads_binary', 'to_frame', 'from_frame',
           'make_connection', 'KernelProc', 'KernelChannels', 'wait_ready', 'ClientQueue', 'KernelMux', 'GatewayKernel',
           'Kernels', 'create_app', 'serve', 'main']

# %% ../nbs/00_core.ipynb #98c8671f
import asyncio, json, logging, os, signal, subprocess, sys, time, uuid
from collections import deque
from contextlib import asynccontextmanager
from pathlib import Path
from tempfile import mkdtemp
import zmq, zmq.asyncio
from jupywire.connect import write_connection_file
from fastcore.basics import xdumps, revive_dates
from jupywire.session import Session, pack_frames, unpack_frames
from starlette.applications import Starlette
from starlette.responses import JSONResponse, Response
from starlette.routing import Route, WebSocketRoute
from starlette.websockets import WebSocketDisconnect

# %% ../nbs/00_core.ipynb #82539e9e
log = logging.getLogger('jupygate')

# %% ../nbs/00_core.ipynb #99c479c2
def dumps(msg:dict)->str:
    "Encode a Jupyter message dict (no buffers) as a websocket text frame."
    return xdumps(msg)

def loads(s:str|bytes)->dict:
    "Decode a websocket text frame back into a message dict, reviving header dates."
    msg = json.loads(s)
    for k in ('header','parent_header'):
        if isinstance(msg.get(k), dict): msg[k] = revive_dates(msg[k])
    return msg


# %% ../nbs/00_core.ipynb #dd69572d
def dumps_binary(msg:dict)->bytes:
    "Encode a message with `buffers` as a legacy-protocol binary frame."
    msg = dict(msg)
    buffers = msg.pop('buffers')
    return pack_frames(dumps(msg).encode('utf-8'), buffers)

def loads_binary(bmsg:bytes)->dict:
    "Decode a legacy-protocol binary frame back into a message dict with `buffers`."
    body, buffers = unpack_frames(bmsg)
    msg = loads(body)
    msg['buffers'] = buffers
    return msg


# %% ../nbs/00_core.ipynb #c2512b33
def to_frame(msg:dict)->str|bytes:
    "Encode `msg` for the websocket: JSON text frame, or binary frame if it carries buffers."
    return dumps_binary(msg) if msg.get('buffers') else dumps({k:v for k,v in msg.items() if k!='buffers'})

def from_frame(data:str|bytes)->dict:
    "Decode a websocket frame (text or binary) into a message dict; `buffers` is always present."
    msg = loads_binary(data) if isinstance(data, (bytes,bytearray)) else loads(data)
    msg.setdefault('buffers', [])
    return msg

# %% ../nbs/00_core.ipynb #b9033343
def make_connection(dir:str|None=None)->tuple[str,dict]:
    "Write a connection file with random free ports and a fresh key; returns `(path, info)`."
    dir = dir or mkdtemp(prefix='jupygate-')
    fname = str(Path(dir)/f"kernel-{uuid.uuid4().hex[:8]}.json")
    return write_connection_file(fname, ip='127.0.0.1', key=uuid.uuid4().hex.encode())

# %% ../nbs/00_core.ipynb #79fa398b
def _sudo(username): 
    helper = os.environ.get('JUPYGATE_SUDO')
    return [helper, username] if helper else ['/usr/bin/sudo','-n','-E','-u',username]

class KernelProc:
    "One kernel process: spawn from an argv template, watch, terminate."
    def __init__(self, argv:list[str], env:dict|None=None, appendenv:dict|None=None, cwd:str|None=None, username:str|None=None):
        self.cfile, self.info = make_connection()
        cmd = [a.format(connection_file=self.cfile) for a in argv]
        if username:
            os.chmod(self.cfile, 0o644)
            cmd = [*_sudo(username), *cmd]
        full_env = dict(os.environ if env is None else env) | (appendenv or {})  # `env` replaces the inherited environment; `appendenv` overlays the base
        full_env['JPY_PARENT_PID'] = str(os.getpid())
        self.proc = subprocess.Popen(cmd, env=full_env, cwd=cwd, start_new_session=True)

    @property
    def pid(self): return self.proc.pid
    def alive(self)->bool: return self.proc.poll() is None
    def interrupt(self): os.kill(self.pid, signal.SIGINT)

    def terminate(self, timeout:float=5.0):
        "SIGTERM then SIGKILL; reaps the process and removes the connection file."
        if self.alive():
            self.proc.terminate()
            try: self.proc.wait(timeout)
            except subprocess.TimeoutExpired:
                self.proc.kill()
                self.proc.wait(timeout)
        Path(self.cfile).unlink(missing_ok=True)

# %% ../nbs/00_core.ipynb #924c967d
IPYMINI_ARGV = [sys.executable, '-m', 'ipymini', '-f', '{connection_file}']

# %% ../nbs/00_core.ipynb #c2ac6fa1
CHANNELS = ('shell','control','stdin','iopub')

class KernelChannels:
    "One persistent set of zmq.asyncio sockets connected to a kernel."
    def __init__(self, info:dict):
        self.session = Session(key=info['key'].encode() if isinstance(info['key'],str) else info['key'])
        self.ctx = zmq.asyncio.Context()
        addr = lambda port: f"{info['transport']}://{info['ip']}:{port}"
        self.socks = {}
        for name in CHANNELS:
            kind = zmq.SUB if name=='iopub' else zmq.DEALER
            s = self.ctx.socket(kind)
            s.linger = 0
            if kind==zmq.DEALER: s.setsockopt(zmq.IDENTITY, self.session.bsession)
            else:
                s.subscribe(b'')
                s.rcvhwm = 0  # before connect. Lossless hop: libzmq's HWM drops silently (statuses included); shedding belongs to ClientQueue alone
            s.connect(addr(info[f'{name}_port']))
            self.socks[name] = s

    async def send(self, channel:str, msg:dict):
        "Sign, serialize, and send a message dict on `channel`, awaiting the socket send so errors and backpressure surface here."
        m = dict(header=msg['header'], parent_header=msg.get('parent_header') or {}, metadata=msg.get('metadata') or {}, content=msg.get('content') or {})
        await self.socks[channel].send_multipart(self.session.serialize(m) + [memoryview(b) for b in msg.get('buffers') or []])

    async def recv(self, channel:str)->dict:
        "Receive and verify one message from `channel` (iopub topic frames are handled)."
        parts = await self.socks[channel].recv_multipart()
        idents, msg_list = self.session.feed_identities(parts)
        return self.session.deserialize(msg_list)

    def close(self):
        for s in self.socks.values(): s.close()
        self.ctx.term()

# %% ../nbs/00_core.ipynb #34e7a2c1
async def wait_ready(ch:KernelChannels, timeout:float=30.0, probe_every:float=0.5)->dict:
    "Block until the kernel answers `kernel_info` and iopub is proven live; returns the kernel_info reply content, leaving both channels clean."
    loop = asyncio.get_running_loop()
    end = loop.time() + timeout
    def left(cap=1.0):
        t = end - loop.time()
        if t <= 0: raise TimeoutError(f"kernel not ready after {timeout}s")
        return min(t, cap)
    async def recv_or_none(channel, cap=1.0):
        if await ch.socks[channel].poll(int(left(cap)*1000)): return await ch.recv(channel)
        return None
    probes = set()
    async def probe():
        m = ch.session.msg('kernel_info_request')
        probes.add(m['header']['msg_id'])
        await ch.send('shell', m)
        return m['header']['msg_id']
    msg = None
    while msg is None:
        await probe()
        msg = await recv_or_none('iopub', probe_every)
    if msg['header']['msg_type'] == 'iopub_welcome':
        mid = await probe()  # end marker: replies are FIFO, so once its reply and idle arrive, every earlier probe's traffic is consumed
        while (reply := await recv_or_none('shell')) is None or reply['parent_header'].get('msg_id') != mid: pass
        while not (msg['header']['msg_type']=='status' and msg['parent_header'].get('msg_id')==mid and msg['content']['execution_state']=='idle'):
            while (msg := await recv_or_none('iopub')) is None: pass
    else:
        while (reply := await recv_or_none('shell')) is None or reply['header']['msg_type'] != 'kernel_info_reply': pass
        outstanding = len(probes) - 1  # every probe gets a reply; one was consumed above
        while outstanding and await ch.socks['shell'].poll(1000):
            m = await ch.recv('shell')
            if m['parent_header'].get('msg_id') in probes: outstanding -= 1
        while await ch.socks['iopub'].poll(200): await ch.recv('iopub')  # then drain iopub until 0.2s of silence
    return reply['content']


# %% ../nbs/00_core.ipynb #41d52e28
class ClientQueue:
    "Outbound queue of encoded frames for one client. The bound governs iopub only, and never drops `status` while attached."
    def __init__(self, session_id:str, send, qmax:int=1000, buffer:bool=True):
        self.session_id, self.qmax, self.buffer = session_id, qmax, buffer
        self.q, self.dropped, self._drop_mark, self._wake = deque(), 0, 0, asyncio.Event()
        self.task = self.detached_at = None
        self.attach(send)

    @property
    def detached(self): return self.detached_at is not None

    def attach(self, send):
        "(Re)bind the queue to a live websocket: install `send` and start a fresh writer."
        if self.task: self.task.cancel()
        self._send, self.detached_at = send, None
        self.task = asyncio.create_task(self._writer())

    def detach(self):
        "Park the queue as a ring: stop the writer, remember when and how much was already dropped."
        if self.task: self.task.cancel()
        self.task, self.detached_at, self._drop_mark = None, time.monotonic(), self.dropped

    def put(self, msg:dict): self.put_frame(msg['header']['msg_type'], to_frame(msg), iopub=msg.get('channel')=='iopub')

    def put_frame(self, msg_type:str, frame:str|bytes, iopub:bool=True):
        if len(self.q) >= self.qmax and (self.detached or (iopub and msg_type!='status')):
            self.dropped += 1
            if self.dropped==1 or self.dropped%1000==0: log.warning("client %s queue full; dropped=%d", self.session_id, self.dropped)
            if not self.detached: return  # attached: the newcomer is dropped
            self.q.popleft()              # detached ring: the oldest is evicted, the newcomer kept
        self.q.append((msg_type, frame))
        self._wake.set()

    def force(self, msg:dict):
        "Queue `msg` past the bound (reattach synthesis: exactly two messages, never more)."
        self.q.append((msg['header']['msg_type'], to_frame(msg)))
        self._wake.set()

    async def _writer(self):
        while True:
            if not self.q:
                self._wake.clear()
                await self._wake.wait()
            try: await self._send(self.q[0][1])
            except Exception: return  # connection gone; the frame stays queued for a reattach
            self.q.popleft()
            await asyncio.sleep(0)  # a buffered transport can complete sends without suspending; yield so cancel and disconnect can land

    def close(self):
        if self.task: self.task.cancel()

# %% ../nbs/00_core.ipynb #01adae60
class KernelMux:
    "Fan kernel traffic out to clients; route client frames back to kernel channels."
    def __init__(self, ch:KernelChannels, qmax:int=1000, buffer_secs:float=3600.0):
        self.ch, self.qmax, self.buffer_secs = ch, qmax, buffer_secs
        self.clients, self.pending_stdin, self.exec_state = {}, {}, 'starting'
        self.tasks = [asyncio.create_task(self._pump(c)) for c in CHANNELS]
        if buffer_secs: self.tasks.append(asyncio.create_task(self._reaper()))

    @property
    def n_attached(self): return sum(1 for cq in self.clients.values() if not cq.detached)

    def add(self, session_id:str, send, buffer:bool=True)->ClientQueue:
        "Register a client, or reattach a returning session to its surviving queue."
        cq = self.clients.get(session_id)
        if cq is None:
            self.clients[session_id] = cq = ClientQueue(session_id, send, self.qmax, buffer=buffer)
            return cq
        missed = cq.dropped - cq._drop_mark if cq.detached else 0
        cq.attach(send)
        if missed:
            warn = self.ch.session.msg('stream', dict(name='stderr', text=f'[jupygate] {missed} messages dropped while disconnected\n'))
            for m in (warn, self.ch.session.msg('status', dict(execution_state=self.exec_state))):
                m['channel'] = 'iopub'
                cq.force(m)
        return cq

    def drop(self, session_id:str):
        "A websocket went away: park the queue if the session is bufferable, else discard it."
        cq = self.clients.get(session_id)
        if cq is None: return
        if self.buffer_secs and cq.buffer: cq.detach()
        else:
            self.clients.pop(session_id)
            cq.close()

    async def _reaper(self):
        while True:
            await asyncio.sleep(min(self.buffer_secs, 60))
            cutoff = time.monotonic() - self.buffer_secs
            for sid, cq in list(self.clients.items()):
                if cq.detached and cq.detached_at < cutoff:
                    self.clients.pop(sid)
                    cq.close()

    async def _pump(self, channel:str):
        while True:
            msg = await self.ch.recv(channel)
            await asyncio.sleep(0)  # zmq recv on a buffered socket completes without suspending; yield so writers and handlers run mid-flood
            msg['channel'] = channel
            if channel=='iopub':
                if msg['header']['msg_type']=='status': self.exec_state = msg['content']['execution_state']
                mt, frame = msg['header']['msg_type'], to_frame(msg)
                for cq in self.clients.values(): cq.put_frame(mt, frame)
                continue
            sid = msg['parent_header'].get('session')
            if channel=='stdin' and msg['header']['msg_type']=='input_request': self.pending_stdin[sid] = msg['header']
            if (cq := self.clients.get(sid)): cq.put(msg)

    async def handle_frame(self, session_id:str, data:str|bytes):
        "One frame from a client websocket: decode, repair stdin parents, send to the kernel."
        msg = from_frame(data)
        channel = msg.pop('channel', 'shell')
        if channel=='stdin' and not msg.get('parent_header') and (hdr := self.pending_stdin.pop(session_id, None)):
            msg['parent_header'] = hdr
        await self.ch.send(channel, msg)

    def synthesize_status(self, state:str):
        "Broadcast a gateway-made status (`restarting`/`dead`): kernels cannot announce their own death."
        self.exec_state = state
        msg = self.ch.session.msg('status', dict(execution_state=state))
        msg['channel'] = 'iopub'
        mt, frame = 'status', to_frame(msg)
        for cq in self.clients.values(): cq.put_frame(mt, frame)

    def close(self):
        for t in self.tasks: t.cancel()
        for cq in self.clients.values(): cq.close()
        self.clients.clear()

# %% ../nbs/00_core.ipynb #16b3d9b0
class GatewayKernel:
    "A kernel process plus its channel set and mux, as one lifecycle."
    def __init__(self, argv:list[str], env:dict|None=None, appendenv:dict|None=None, cwd:str|None=None,
        username:str|None=None, qmax:int=1000, buffer_secs:float=3600.0):
        self.spec = dict(argv=argv, env=env, appendenv=appendenv, cwd=cwd, username=username)
        self.qmax, self.buffer_secs = qmax, buffer_secs
        self.id = uuid.uuid4().hex
        self.proc = self.ch = self.mux = self._watcher = None
        self.state = 'starting'

    async def start(self, timeout:float=60.0):
        self.proc = KernelProc(**self.spec)
        self.ch = KernelChannels(self.proc.info)
        await wait_ready(self.ch, timeout)
        self.mux = KernelMux(self.ch, qmax=self.qmax, buffer_secs=self.buffer_secs)
        self.state = 'alive'
        self._watcher = asyncio.create_task(self._watch())
        return self

    async def _watch(self):
        while self.proc.alive(): await asyncio.sleep(0.5)
        if self.state=='alive':
            self.state = 'dead'
            self.mux.synthesize_status('dead')

    def model(self)->dict: return dict(id=self.id, name='', execution_state=self.state, connections=self.mux.n_attached if self.mux else 0)
    def interrupt(self): self.proc.interrupt()

    async def restart(self, timeout:float=60.0):
        self.state = 'restarting'
        self.mux.synthesize_status('restarting')
        old_mux = self.mux
        clients, old_mux.clients = old_mux.clients, {}
        await self.shutdown(keep_state=True)
        old_mux.close()
        await self.start(timeout)
        self.mux.clients = clients
        self.mux.synthesize_status('starting')

    async def shutdown(self, keep_state:bool=False):
        if self._watcher: self._watcher.cancel()
        if not keep_state:
            self.state = 'dead'
            if self.mux: self.mux.close()
        if self.ch: self.ch.close()
        if self.proc: await asyncio.to_thread(self.proc.terminate)

# %% ../nbs/00_core.ipynb #94e4031d
class Kernels:
    "Kernel registry: create, look up, and reap `GatewayKernel`s. The HTTP app and embedders both drive this."
    def __init__(self, argv:list[str]=IPYMINI_ARGV, qmax:int=1000, buffer_secs:float=3600.0):
        self.argv, self.qmax, self.buffer_secs = argv, qmax, buffer_secs
        self.kernels = {}

    async def create(self, argv:list[str]|None=None, env:dict|None=None, appendenv:dict|None=None,
        cwd:str|None=None, username:str|None=None, timeout:float=60.0)->GatewayKernel:
        gk = GatewayKernel(argv=argv or self.argv, env=env, appendenv=appendenv, cwd=cwd, username=username, qmax=self.qmax, buffer_secs=self.buffer_secs)
        self.kernels[gk.id] = gk
        try: await gk.start(timeout)
        except Exception:
            self.kernels.pop(gk.id, None)
            await gk.shutdown()
            raise
        return gk

    async def delete(self, kid:str):
        gk = self.kernels.pop(kid)
        await gk.shutdown()

    async def shutdown(self):
        "Reap every kernel; nothing survives the registry."
        await asyncio.gather(*[k.shutdown() for k in self.kernels.values()], return_exceptions=True)
        self.kernels.clear()

    def get(self, kid:str)->GatewayKernel|None: return self.kernels.get(kid)
    def values(self): return self.kernels.values()
    def __getitem__(self, kid:str)->GatewayKernel: return self.kernels[kid]
    def __len__(self): return len(self.kernels)

# %% ../nbs/00_core.ipynb #32c30a8f
def _authed(request, token):
    if not token: return True
    hdr = request.headers.get('authorization', '')
    return hdr == f'token {token}' or request.query_params.get('token') == token

def create_app(argv:list[str]=IPYMINI_ARGV, auth_token:str|None=None, qmax:int=1000, buffer_secs:float=3600.0)->Starlette:
    "The gateway app. `argv` is the default kernel command; creation requests may override it."
    kernels = Kernels(argv, qmax=qmax, buffer_secs=buffer_secs)

    def _kernel(request):
        k = kernels.get(request.path_params['kid'])
        if k is None: raise KeyError
        return k

    async def list_kernels(request): return JSONResponse([k.model() for k in kernels.values()])

    async def create_kernel(request):
        body = await request.json() if await request.body() else {}
        try: gk = await kernels.create(argv=body.get('argv'), env=body.get('env'), appendenv=body.get('appendenv'), cwd=body.get('cwd'), username=body.get('username'))
        except Exception as e: return JSONResponse(dict(message=f'kernel failed to start: {e}'), status_code=500)
        return JSONResponse(gk.model(), status_code=201)

    async def get_kernel(request): return JSONResponse(_kernel(request).model())

    async def delete_kernel(request):
        await kernels.delete(request.path_params['kid'])
        return Response(status_code=204)

    async def interrupt(request):
        _kernel(request).interrupt()
        return Response(status_code=204)

    async def restart(request):
        gk = _kernel(request)
        await gk.restart()
        return JSONResponse(gk.model())

    async def channels(ws):
        if not _authed(ws, auth_token): return await ws.close(code=4403)
        gk = kernels.get(ws.path_params['kid'])
        if gk is None or gk.mux is None: return await ws.close(code=4404)
        sid = ws.query_params.get('session_id')
        sid, buffer = sid or uuid.uuid4().hex, sid is not None
        await ws.accept()
        async def send(frame):
            if isinstance(frame, bytes): await ws.send_bytes(frame)
            else: await ws.send_text(frame)
        gk.mux.add(sid, send, buffer=buffer)
        try:
            while True:
                event = await ws.receive()
                if event['type']=='websocket.disconnect': break
                try: await gk.mux.handle_frame(sid, event.get('bytes') or event['text'])
                except Exception as e: log.warning('dropped frame from %s: %s', sid, e)
        except WebSocketDisconnect: pass
        finally: gk.mux.drop(sid)

    def guard(fn):
        async def inner(request):
            if not _authed(request, auth_token): return JSONResponse(dict(message='forbidden'), status_code=403)
            try: return await fn(request)
            except KeyError: return JSONResponse(dict(message='no such kernel'), status_code=404)
        return inner

    @asynccontextmanager
    async def lifespan(app):
        yield
        await kernels.shutdown()

    r = lambda p,meth,f: Route('/api/kernels'+p, guard(f), methods=[meth])
    app = Starlette(lifespan=lifespan, routes=[r('','GET',list_kernels), r('','POST',create_kernel), r('/{kid}','GET',get_kernel),
        r('/{kid}','DELETE',delete_kernel), r('/{kid}/interrupt','POST',interrupt), r('/{kid}/restart','POST',restart),
        WebSocketRoute('/api/kernels/{kid}/channels', channels)])
    app.state.kernels = kernels
    return app

# %% ../nbs/00_core.ipynb #2515195d
def serve(app, host:str='127.0.0.1', port:int=8787, log_level:str='warning', in_thread:bool=False):
    "Run the gateway under uvicorn; `in_thread=True` waits until it is listening and returns the server with `server.url` set (`port=0` picks a free port)."
    import threading, time, uvicorn
    server = uvicorn.Server(uvicorn.Config(app, host=host, port=port, log_level=log_level, ws_max_size=64*2**20))
    if not in_thread:
        server.run()
        return server
    server.thread = threading.Thread(target=server.run, daemon=True)
    server.thread.start()
    end = time.monotonic() + 10
    while not server.started:
        if time.monotonic() > end: raise TimeoutError('uvicorn did not start')
        time.sleep(0.01)
    server.url = f'http://{host}:{server.servers[0].sockets[0].getsockname()[1]}'
    return server

def _env_app():
    "App factory for the reloader: its fresh workers re-import this module, so config rides in the environment; the token is popped so spawned kernels never inherit it"
    return create_app(auth_token=os.environ.pop('JUPYGATE_TOKEN', None))

def _reload_file():
    "The restart lever: touching this file restarts the gateway, killing all kernels; created at startup so it is always touchable"
    from fastcore.xdg import xdg_state_home
    p = xdg_state_home()/'jupygate'/'reload'/'r.py'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.touch()
    return p

def main():
    "Console entry point: `jupygate [--port N] [--token T] [--reload]`."
    import argparse, uvicorn
    from uvicorn.supervisors import ChangeReload
    p = argparse.ArgumentParser(description='Websocket gateway for Jupyter kernels')
    p.add_argument('--host', default='127.0.0.1')
    p.add_argument('--port', type=int, default=8787)
    p.add_argument('--token', default=None)
    p.add_argument('--reload', action='store_true', help='also restart on package source changes (dev)')
    args = p.parse_args()
    if args.token: os.environ['JUPYGATE_TOKEN'] = args.token
    reload_dirs = [str(_reload_file().parent)]
    if args.reload: reload_dirs.append(str(Path(__file__).parent))
    config = uvicorn.Config('jupygate.core:_env_app', factory=True, reload=True, reload_dirs=reload_dirs,
        host=args.host, port=args.port, log_level='warning', ws_max_size=64*2**20, timeout_graceful_shutdown=5)
    server = uvicorn.Server(config)
    try: ChangeReload(config, target=server.run, sockets=[config.bind_socket()]).run()
    except KeyboardInterrupt: pass
