"""Terminals: gateway-hosted ptys, siblings of kernels

Kernels moved behind the gateway, but the terminal features of jupygate's clients (solveit's embedded terminal, ipyai's shell mode) spawn ptys in their own process — the wrong side of the gateway the moment the kernel is remote. A terminal must live where the kernel lives: same machine, container, and filesystem. So terminals are a gateway resource, siblings of kernels, mirroring [jupyter's terminals API](https://github.com/jupyter-server/jupyter_server_terminals): named terminals you can list, create, delete, and attach to over a websocket — with replay on reattach, so a page refresh or dropped connection resumes the *same* shell with recent scrollback. The pty sessions themselves are [ptymini](https://github.com/AnswerDotAI/ptymini)'s (`PtySession`/`PtyRegistry`, extracted from here); this module owns what is genuinely the gateway's: the REST translation, the websocket framing, auth, and privilege policy (`_sudo`). Design notes and the choreography audit live in `meta/TERM.md`.

The websocket framing is bytes-native rather than [terminado](https://github.com/jupyter/terminado)'s JSON-of-decoded-text: binary frames carry pty bytes verbatim in both directions, and text frames carry JSON control messages. Client parsers that watch the stream for escape sequences (ipyai's sentinel choreography) need the raw bytes; decode/re-encode is a fidelity risk with nothing bought.

Docs: https://AnswerDotAI.github.io/jupygate/term.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_term.ipynb.

# %% auto #0
__all__ = ['term_routes']

# %% ../nbs/01_term.ipynb #e7bcf949
import asyncio, json
from starlette.responses import JSONResponse, Response
from starlette.routing import Route, WebSocketRoute
from ptymini.core import PtyRegistry, Gap
from .core import _authed, _sudo


# %% ../nbs/01_term.ipynb #bf4d92c9
def term_routes(terminals:PtyRegistry, auth_token:str|None=None)->list:
    "Starlette routes for the terminals API, against one ptymini `PtyRegistry`."
    async def list_terms(request): return JSONResponse([t.model() for t in terminals.values()])

    async def create_term(request):
        body = await request.json() if await request.body() else {}
        kw = {k: body[k] for k in ('name','argv','cwd','env','appendenv','rc','rows','cols') if k in body}
        if body.get('username'): kw['argv'] = [*_sudo(body['username']), *(kw.get('argv') or terminals.argv)]
        try: t = await terminals.create(**kw)
        except Exception as e: return JSONResponse(dict(message=f'terminal failed to start: {e}'), status_code=500)
        return JSONResponse(t.model(), status_code=201)

    async def get_term(request): return JSONResponse(terminals.terms[request.path_params['name']].model())

    async def delete_term(request):
        await terminals.delete(request.path_params['name'])
        return Response(status_code=204)

    async def channel(ws):
        if not _authed(ws, auth_token): return await ws.close(code=4403)
        t = terminals.get(ws.path_params['name'])
        if t is None: return await ws.close(code=4404)
        await ws.accept()
        await ws.send_text(json.dumps(dict(type='setup', name=t.name)))
        async def pump():
            async for item in t.attach(gaps=True):
                if isinstance(item, Gap): await ws.send_text(json.dumps(dict(type='gap', bytes=int(item))))
                else: await ws.send_bytes(item)
            await ws.send_text(json.dumps(dict(type='eof', code=t.exit_code)))
        task = asyncio.create_task(pump())
        try:
            while True:
                event = await ws.receive()
                if event['type'] == 'websocket.disconnect': break
                if event.get('bytes'): t.write(event['bytes'])
                elif event.get('text'):
                    c = json.loads(event['text'])
                    if c.get('type') == 'set_size': t.resize(c['rows'], c['cols'])
        finally: task.cancel()

    def guard(fn):
        async def inner(request):
            if not _authed(request, auth_token): return JSONResponse(dict(message='forbidden'), status_code=403)
            try: return await fn(request)
            except KeyError: return JSONResponse(dict(message='no such terminal'), status_code=404)
        return inner

    r = lambda p,meth,f: Route('/api/terminals'+p, guard(f), methods=[meth])
    return [r('','GET',list_terms), r('','POST',create_term), r('/{name}','GET',get_term),
        r('/{name}','DELETE',delete_term), WebSocketRoute('/api/terminals/{name}/channel', channel)]
