"""Host terminal ptys on the gateway alongside kernels

A terminal for a remote kernel needs to run on the same machine, in the same container and filesystem. Spawning the shell in a client process puts it in the wrong environment. Solveit's embedded terminal and ipyai's shell mode need a gateway connection for this reason.

Jupygate hosts named terminals alongside its kernels. Clients can list, create, and delete terminals through [Jupyter's terminals REST API](https://github.com/jupyter-server/jupyter_server_terminals). They attach to a running terminal over a websocket. Reconnecting after a page refresh or dropped connection resumes the same shell and replays recent scrollback.

[Ptymini](https://github.com/AnswerDotAI/ptymini) manages the pty sessions with `PtySession` and `PtyRegistry`. Those classes originally lived here. This module translates REST requests and websocket frames into ptymini calls. It checks authentication and applies user privileges through `_sudo`. The design notes and ipyai's stream-parsing requirements are in `meta/TERM.md`.

The websocket sends pty bytes unchanged in both directions. Text frames contain JSON control messages. This differs from [terminado](https://github.com/jupyter/terminado), which sends decoded terminal text inside JSON. Ipyai identifies command boundaries by parsing escape sequences in the byte stream. Decoding and re-encoding could alter those bytes. The gateway leaves them intact.

Docs: https://AnswerDotAI.github.io/jupygate/term.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_term.ipynb.

# %% auto #0
__all__ = ['term_routes']

# %% ../nbs/01_term.ipynb #e7bcf949
import asyncio, json
from starlette.responses import JSONResponse, Response
from starlette.routing import Route, WebSocketRoute
from ptymini.core import PtyRegistry, Gap
from .core import _authed, _sudo


# %% ../nbs/01_term.ipynb #bf4d92c9
def term_routes(terminals:PtyRegistry, auth_token:str|None=None)->list:
    "Starlette routes for the terminals API, against one ptymini `PtyRegistry`."
    async def list_terms(request): return JSONResponse([t.model() for t in terminals.values()])

    async def create_term(request):
        body = await request.json() if await request.body() else {}
        kw = {k: body[k] for k in ('name','argv','cwd','env','appendenv','rc','rows','cols') if k in body}
        if body.get('username'): kw['argv'] = [*_sudo(body['username']), *(kw.get('argv') or terminals.argv)]
        try: t = await terminals.create(**kw)
        except Exception as e: return JSONResponse(dict(message=f'terminal failed to start: {e}'), status_code=500)
        return JSONResponse(t.model(), status_code=201)

    async def get_term(request): return JSONResponse(terminals.terms[request.path_params['name']].model())

    async def delete_term(request):
        await terminals.delete(request.path_params['name'])
        return Response(status_code=204)

    async def channel(ws):
        if not _authed(ws, auth_token): return await ws.send_denial_response(JSONResponse(dict(message='forbidden'), status_code=403))
        t = terminals.get(ws.path_params['name'])
        if t is None: return await ws.send_denial_response(JSONResponse(dict(message='no such terminal'), status_code=404))
        await ws.accept()
        await ws.send_text(json.dumps(dict(type='setup', name=t.name)))
        async def pump():
            async for item in t.attach(gaps=True):
                if isinstance(item, Gap): await ws.send_text(json.dumps(dict(type='gap', bytes=int(item))))
                else: await ws.send_bytes(item)
            await ws.send_text(json.dumps(dict(type='eof', code=t.exit_code)))
        task = asyncio.create_task(pump())
        try:
            while True:
                event = await ws.receive()
                if event['type'] == 'websocket.disconnect': break
                if event.get('bytes'): t.write(event['bytes'])
                elif event.get('text'):
                    c = json.loads(event['text'])
                    if c.get('type') == 'set_size': t.resize(c['rows'], c['cols'])
        finally: task.cancel()

    def guard(fn):
        async def inner(request):
            if not _authed(request, auth_token): return JSONResponse(dict(message='forbidden'), status_code=403)
            try: return await fn(request)
            except KeyError: return JSONResponse(dict(message='no such terminal'), status_code=404)
        return inner

    r = lambda p,meth,f: Route('/api/terminals'+p, guard(f), methods=[meth])
    return [r('','GET',list_terms), r('','POST',create_term), r('/{name}','GET',get_term),
        r('/{name}','DELETE',delete_term), WebSocketRoute('/api/terminals/{name}/channel', channel)]
